all:
	rm -rf build
	mkdir build

	gcc writer1.c constants.c -o build/writer1
	gcc writer2.c constants.c -o build/writer2
	gcc reader1.c constants.c -o build/reader1
	gcc reader2.c constants.c -o build/reader2
