all:
	rm -rf build
	mkdir build

	gcc writer1.c -o build/writer1 -Wno-extern-initializer
	gcc writer2.c -o build/writer2 -Wno-extern-initializer
	gcc reader1.c -o build/reader1 -Wno-extern-initializer
	gcc reader2.c -o build/reader2 -Wno-extern-initializer
